version: '2'
services:
  mongodb:
    container_name: customer-datastore
    image: mongo:3.2
    command: mongod --smallfiles
  web:
    container_name: customer-service
    build: target #folder wher build information is
    image: customer-image
    depends_on: # customer-datastore will be started before the schools-service
      - mongodb
    ports:
      - "8080:12347" # port mapping
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test