version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4.2
    command: mongod --smallfiles
    hostname: mongodb
    ports: 
      - "27017:27017"
      
  Eureka:
    container_name: Eureka
    build: ./Eureka
    depends_on:
      - "mongodb"
    image: eureka
    links:
      - "mongodb"
    hostname: Eureka
    ports: 
      - "8761:8761"
      
  patientrecords:
    container_name: patientrecords
    build: ./PatientRecords
    depends_on:
      - "Eureka"
    image: patientrecords
    volumes:
      - ./patientrecords:/app
    hostname: patientrecords
    links:
      - mongodb:mongodb
      - Eureka:Eureka
    ports:
      - "12349:12349"
  
#  api:
#    container_name: api
#    build: ./PatientAPI
#    depends_on:
#      - "Eureka"
#    image: patientapi-service
#    volumes:
#      - ./apigateway:/app
#    hostname: api
#    links:
#      - mongodb:mongodb
#      - Eureka:Eureka
#    ports: 
#      - "12355:12355"
